from enum import Enum

class UserAccountType(str, Enum):
    USER_ACCOUNT_TYPE_BASIC = 'USER_ACCOUNT_TYPE_BASIC'
    USER_ACCOUNT_TYPE_COMMERCIAL = 'USER_ACCOUNT_TYPE_COMMERCIAL'
    USER_ACCOUNT_TYPE_ENTERPRISE = 'USER_ACCOUNT_TYPE_ENTERPRISE'
