import logging

class AieException(Exception):

    INVALID_INPUT_DATA = "INVALID_INPUT_DATA"
    NO_BUILDING_POLYGON_WIDER_AREA = "NO_BUILDING_POLYGON_WIDER_AREA"
    CONSUMPTION_TOO_LOW = "CONSUMPTION_TOO_LOW"
    NO_BUILDING_POLYGON = "NO_BUILDING_POLYGON"
    GENERIC_PYTHON_ERROR = "GENERIC_PYTHON_ERROR"
    ROOFTOP_PLOTTING_ERROR = "ROOFTOP_PLOTTING_ERROR"
    HOUSE_NOT_LOCATED = "HOUSE_NOT_LOCATED"
    HOUSE_TOO_LARGE = "HOUSE_TOO_LARGE"
    ROOFTOP_ALGORITHM_FAILED = "ROOFTOP_ALGORITHM_FAILED"
    BUILDING_NOT_FOUND_ON_OSM = "BUILDING_NOT_FOUND_ON_OSM"
    COUNTRY_NOT_SUPPORTED_FOR_OPTIMIZATION = "COUNTRY_NOT_SUPPORTED_FOR_OPTIMIZATION"
    COUNTRY_NOT_SUPPORTED = "COUNTRY_NOT_SUPPORTED"
    NO_CONSUMPTION_PROVIDED = "NO_CONSUMPTION_PROVIDED"

    logMessage: str

    def __init__(self, message, logMessage = None):
        super().__init__(message)

        if (logMessage is None):
            self.logMessage = message
        else:
            self.logMessage = logMessage

        logging.info(f"AinException: {self.logMessage}")
